// ==UserScript==
// @name         GrepBot
// @namespace    grepbot
// @version      4.58.1
// @description  Automatizacion de Grepolis: explorar/granjas/construir/comerciar/cultura/reclutar. Los ToS prohiben la automatizacion; riesgo = ban.
// @author       j
// @match        https://*.grepolis.com/*
// @run-at       document-idle
// @noframes
// @grant        GM_xmlhttpRequest
// @grant        GM_setValue
// @grant        GM_getValue
// @grant        GM_addStyle
// @grant        GM_registerMenuCommand
// @grant        GM_unregisterMenuCommand
// @connect      grepolis.com
// @connect      discord.com
// @connect      discordapp.com
// @connect      api.telegram.org
// ==/UserScript==

(function () {
  'use strict';
const STORE = {
    FINDINGS: 'grepbot:findings',
    FARMS:    'grepbot:farms',
    FARMS_PARSED: 'grepbot:farms-parsed',
    FARM_RES: 'grepbot:resources',
    SEEN:     'grepbot:seen',
    TOWNS:    'grepbot:towns',
    TOWN_RES: 'grepbot:town-resources',
    THRESH:   'grepbot:thresholds',
    ALERTED:  'grepbot:alerted',
    COLLECT_ALL: 'grepbot:collect-all',
    COLLECT_TPL: 'grepbot:collect-tpl',
    AUTO_BANDIT: 'grepbot:auto-bandit',
    BANDIT_CFG: 'grepbot:bandit-cfg',
    BANDIT_LOG:  'grepbot:bandit-log',
    NEXT_FARM:  'grepbot:next-farm',
    NEXT_TOWNS: 'grepbot:next-towns',
    FARM_ACTION: 'grepbot:farm-action',
    AUTO_FARM:  'grepbot:auto-farm',
    CLAIM_TPL:  'grepbot:claim-tpl',
    IB_AUTO:   'grepbot:ib-auto',
    IB_FREE_THRESH: 'grepbot:ib-free-thresh',
    QUEST_REWARDS: 'grepbot:quest-rewards',
    QUEST_AUTO_BUILD: 'grepbot:quest-auto-build',
    QUEST_AUTO_RES: 'grepbot:quest-auto-res',
    QUEST_HISTORY: 'grepbot:quest-history',
    COLLECT_MAX_MIN: 'grepbot:collect-max-min',
    FARM_MIN: 'grepbot:farm-min-ms',
    FARM_MAX: 'grepbot:farm-max-ms',
    TOWN_MIN: 'grepbot:town-min-ms',
    TOWN_MAX: 'grepbot:town-max-ms',
    ENABLED_HOSTS: 'grepbot:enabled-hosts',
    ATTACK_TPL: 'grepbot:attack-tpl',
    CANCEL_TPL: 'grepbot:cancel-tpl',
    HERO_TPL: 'grepbot:hero-tpl',
    AUTO_HERO: 'grepbot:auto-hero',
    HERO_LOW_STAMINA_PCT: 'grepbot:hero-low-stamina-pct',
    HERO_EQUIP_SUGGEST: 'grepbot:hero-equip-suggest',
    ATTACK_PLAN: 'grepbot:attack-plan',
    ATTACK_HISTORY: 'grepbot:attack-history',
    ATTACK_RECENT: 'grepbot:attack-recent',
    CAPTCHA: 'grepbot:captcha-breakers',
    FINDINGS_FILTER: 'grepbot:findings-filter',
    PANEL_GEOM: 'grepbot:panel-geom',
    WIDGET_GEOM: 'grepbot:widget-geom',
    HUD_PRODUCTION: 'grepbot:hud-production',
    HUD_COUNTDOWN: 'grepbot:hud-countdown',
    TOWN_GROWTH_HIST: 'grepbot:town-growth-hist',
    THEME: 'grepbot:theme',
    CONTEXT_MENU: 'grepbot:context-menu',
    PROFILE_AUTO_CFG: 'grepbot:profile-auto-cfg',
    PROFILE_AUTO_LAST: 'grepbot:profile-auto-last',
    KEYBINDINGS: 'grepbot:keybindings',
    KEYBOARD_SHORTCUTS: 'grepbot:keyboard-shortcuts',
    ACTIVE_TAB: 'grepbot:active-tab',
    CSRF: 'grepbot:csrf',
    FARM_SKIP_FULL: 'grepbot:farm-skip-full',
    FARM_FULL_MODE: 'grepbot:farm-full-mode',
    AB_AUTO: 'grepbot:ab-auto',
    AUTO_WALL_REPAIR: 'grepbot:auto-wall-repair',
    AB_TARGETS: 'grepbot:ab-targets',
    AUTO_CAVE: 'grepbot:auto-cave',
    CAVE_THRESH: 'grepbot:cave-thresh',
    CAVE_TOWNS: 'grepbot:cave-towns',
    EMERGENCY_CAVE_AUTO: 'grepbot:emergency-cave-auto',
    EMERGENCY_CAVE_CONFIRM: 'grepbot:emergency-cave-confirm',
    EMERGENCY_CAVE_MIN: 'grepbot:emergency-cave-min',
    EMERGENCY_LAST: 'grepbot:emergency-last-stash',
    IB_ACTION: 'grepbot:ib-action',
    IB_RESEARCH: 'grepbot:ib-research',
    FARM_OPTION_MAP: 'grepbot:farm-option-map',
    FARM_LONG_CLAIMS: 'grepbot:farm-long-claims',
    FARM_LOYALTY_TECH: 'grepbot:farm-loyalty-tech',
    FARM_SLEEP_DUR: 'grepbot:farm-sleep-dur',
    FARM_SLEEP_AUTO: 'grepbot:farm-sleep-auto',
    FARM_SLEEP_FILL: 'grepbot:farm-sleep-fill',
    FARM_SLEEP_DAY: 'grepbot:farm-sleep-day',
    FARM_PROFIT: 'grepbot:farm-profit',
    ADAPTIVE_FARM: 'grepbot:adaptive-farm',
    FARM_DROP_PCT: 'grepbot:farm-drop-pressure-pct',
    FARM_CLAIMS_TODAY: 'grepbot:farm-claims-today',
    FARM_CLAIMS_DAY: 'grepbot:farm-claims-day',
    FARM_TRAVEL: 'grepbot:farm-travel-sec-per-unit',
    IB_ACTION_R: 'grepbot:ib-action-r',

    AUTO_CULTURE: 'grepbot:auto-culture',
    CULTURE_TYPES: 'grepbot:culture-types',
    ALLOW_PREMIUM_CULTURE: 'grepbot:allow-premium-culture',
    CULTURE_GOLD_BUDGET: 'grepbot:culture-gold-budget',
    CULTURE_GOLD_SPENT: 'grepbot:culture-gold-spent',
    AUTO_TRADE: 'grepbot:auto-trade',
    TRADE_PRESET: 'grepbot:trade-preset',
    TRADE_RESERVE: 'grepbot:trade-reserve',
    TRADE_MIN: 'grepbot:trade-min',
    TRADE_ROUTES: 'grepbot:trade-routes',
    AUTO_TRADE_ROUTES: 'grepbot:auto-trade-routes',
    AUTO_TRANSPORT: 'grepbot:auto-transport',
    AUTO_TRANSPORT_AI: 'grepbot:auto-transport-ai',
    AUTO_DUMP: 'grepbot:auto-dump',
    DUMP_THRESHOLD: 'grepbot:dump-threshold',
    DUMP_KEEP: 'grepbot:dump-keep',
    DUMP_SINKS: 'grepbot:dump-sinks',
    TRANSPORT_RESERVE: 'grepbot:transport-reserve',
    TRANSPORT_MIN: 'grepbot:transport-min',
    AUTO_RURAL_TRADE: 'grepbot:auto-rural-trade',
    RURAL_TRADE_RATIO: 'grepbot:rural-trade-ratio',
    RURAL_TRADE_RES: 'grepbot:rural-trade-res',
    AUTO_RURAL_LEVEL: 'grepbot:auto-rural-level',
    RURAL_LEVEL_MAX: 'grepbot:rural-level-max',
    AUTO_RESEARCH: 'grepbot:auto-research',
    RESEARCH_TARGETS: 'grepbot:research-targets',
    PAUSE_ON_ACTIVITY: 'grepbot:pause-on-activity',
    PAUSE_ACTIVITY_MS: 'grepbot:pause-activity-ms',
    NIGHT_PAUSE: 'grepbot:night-pause',
    NIGHT_START: 'grepbot:night-start',
    NIGHT_END: 'grepbot:night-end',
    CITY_TEMPLATES: 'grepbot:city-templates',
    TOWN_GROUPS: 'grepbot:town-groups',
    WEBHOOK_URL: 'grepbot:webhook-url',
    WEBHOOK_EVENTS: 'grepbot:webhook-events',
    NOTIFY_ENABLED: 'grepbot:notify-enabled',
    NOTIFY_EVENTS: 'grepbot:notify-events',
    NOTIFY_VOLUME: 'grepbot:notify-volume',
    NOTIFY_MUTED: 'grepbot:notify-muted',
    AUTO_MERCHANT: 'grepbot:auto-merchant',
    MERCHANT_WISH: 'grepbot:merchant-wish',
    AUTO_FAVOR: 'grepbot:auto-favor',
    FAVOR_CFG: 'grepbot:favor-cfg',
    AUTO_WONDER: 'grepbot:auto-wonder',
    WONDER_CFG: 'grepbot:wonder-cfg',
    AUTO_DODGE: 'grepbot:auto-dodge',
    DODGE_MODE: 'grepbot:dodge-mode',
    DODGE_FLOOR: 'grepbot:dodge-floor',
    AUTO_RECRUIT: 'grepbot:auto-recruit',
    RECRUIT_TARGETS: 'grepbot:recruit-targets',
    RECRUIT_SPELLS: 'grepbot:recruit-spells',
    PRIORITY_ORDER: 'grepbot:priority-order',
    ISLAND_SHIP: 'grepbot:island-ship',
    AUTO_MILITIA: 'grepbot:auto-militia',
    MILITIA_CFG: 'grepbot:militia-cfg',
    CS_ALERT: 'grepbot:cs-alert',
    PLAYER_NOTES: 'grepbot:player-notes',
    WATCHLIST: 'grepbot:watchlist',
    AUTO_SPY: 'grepbot:auto-spy',
    SPY_CFG: 'grepbot:spy-cfg',
    SPY_HISTORY: 'grepbot:spy-history',
    SPY_TPL: 'grepbot:spy-tpl',
    GREPODATA_INDEX: 'grepbot:grepodata-index',
    CAPTCHA_GLOBAL: 'grepbot:captcha-global',
    CAPTCHA_GLOBAL_UNTIL: 'grepbot:captcha-global-until',
    REQ_BUDGET: 'grepbot:req-budget',
    ALLIANCE_NOTES: 'grepbot:alliance-notes',
    NAP_STATUS: 'grepbot:nap-status',
    INTEL_DIGEST: 'grepbot:intel-digest',
    INTEL_ALLY_FILTER: 'grepbot:intel-alliance-filter',
    INTEL_BATTLE_STATS: 'grepbot:intel-battle-stats',
    CONFIG_VER: 'grepbot:config-ver',
    CONFIG_UNDO: 'grepbot:config-undo',
    CONFIG_REDO: 'grepbot:config-redo',
    WONDER_SPENT: 'grepbot:wonder-spent',

    DECISIONS: 'grepbot:decisions',
    DECISION_SKIPS: 'grepbot:decision-skips',
    DECISION_MEM: 'grepbot:decision-memory',
    DRY_RUN: 'grepbot:dry-run',
    RELAY_CMDS: 'grepbot:relay-commands',
    RELAY_RAW: 'grepbot:relay-raw',
    RELAY_ARM_UNTIL: 'grepbot:relay-arm-until',
    RELAY_ARM_MIN: 'grepbot:relay-arm-min',
    RELAY_WRITE_CAP: 'grepbot:relay-write-cap',
    EXPORT_REDACT: 'grepbot:export-redact',
    ORCH_ADAPTIVE: 'grepbot:orch-adaptive',
    SERVER_COOLDOWN: 'grepbot:server-cooldown',
    QUEST_CLAIM_FAIL: 'grepbot:quest-claim-fail',
    DODGE_QUEUE: 'grepbot:dodge-queue',
    AUTO_COLLECT: 'grepbot:auto-collect',
    TX_STATE: 'grepbot:tx-state',
    CIRCUITS: 'grepbot:circuits',
    CIRCUIT_AUTO_CLEAR: 'grepbot:circuit-auto-clear',
    AB_ORDER: 'grepbot:ab-order',
    AB_OPTIMAL_ORDER: 'grepbot:ab-optimal-order',
    AB_OPTIMAL_ORDER_ON: 'grepbot:ab-optimal-order-on',
    PLANNER_CFG: 'grepbot:planner-cfg',
    GOAL_PROFILES: 'grepbot:goal-profiles',
    TOWN_GOALS: 'grepbot:town-goals',
    VIRTUAL_QUEUE: 'grepbot:virtual-queue',
    VIRTUAL_QUEUE_OVERRIDES: 'grepbot:virtual-queue-overrides',
    NATIVE_QUEUE: 'grepbot:native-action-queue',
    BUILD_SWAP_MIN: 'grepbot:build-swap-threshold-min',
    BUILD_SWAP_IGNORE: 'grepbot:build-swap-ignore',
    PREDICT_CFG: 'grepbot:predict-cfg',
    DEFENSE_CFG: 'grepbot:defense-cfg',
    DEFENSE_HISTORY: 'grepbot:defense-history',
    SUPPORT_CFG: 'grepbot:support-cfg',
    SUPPORT_LAST_SEND: 'grepbot:support-last-send',
    SUPPORT_TEMPLATE: 'grepbot:support-tpl',
    DODGE_RETURNS: 'grepbot:dodge-returns',
    HEALTH: 'grepbot:health',
    SNAPSHOTS: 'grepbot:snapshots',
    SNAPSHOTS_ON: 'grepbot:snapshots-on',
    PROFILER_ON: 'grepbot:profiler-on',
    MEM_PROBE_ON: 'grepbot:mem-probe-on',
    CLIENT_FP: 'grepbot:client-fingerprint',
    SAFE_MODE: 'grepbot:safe-mode',
    SIM_CFG: 'grepbot:sim-cfg',
    WHY_LOG: 'grepbot:why-log',
    TPL_HEALTH: 'grepbot:tpl-health',
    CAPTCHA_LADDER: 'grepbot:captcha-ladder',
    POSTS_SOFT_PCT: 'grepbot:posts-soft-pct',
    TAB_FILTERS: 'grepbot:tab-filters',
    ORCH_DEADLOCK: 'grepbot:orch-deadlock',
    FARM_LOYALTY_SEEN: 'grepbot:farm-loyalty-seen',
    FARM_TEACH_BANNER: 'grepbot:farm-teach-banner',
    LAST_SEEN_TS: 'grepbot:last-seen-ts',
    WATCH_HITS: 'grepbot:watch-hits',
    WONDER_FAVOR_TPL: 'grepbot:wonder-favor-tpl',
    AUTO_WONDER_FAVOR: 'grepbot:auto-wonder-favor',
    AUTO_PT_TRADE: 'grepbot:auto-pt-trade',
    PT_CFG: 'grepbot:pt-cfg',
    PT_TRADE_TPL: 'grepbot:pt-trade-tpl',
    PT_VIEW_URL: 'grepbot:pt-view-url',
    SPELL_COOLDOWN: 'grepbot:spell-cooldown',
    FARM_SCRAPE: 'grepbot:farm-scrape',
    TOWN_ACTION: 'grepbot:town-action',
    TOWN_LIST_ACTION: 'grepbot:town-list-action',
    FARM_SCRAPE_STATE: 'grepbot:farm-scrape-state',
    AUTO_VILLAGE_RECRUIT: 'grepbot:auto-village-recruit',
    VILLAGE_RECRUIT_FILL: 'grepbot:village-recruit-fill',
    VILLAGE_RECRUIT_AMOUNT: 'grepbot:village-recruit-amount',
    ACCEPT_UNITS_TPL: 'grepbot:accept-units-tpl',
    VILLAGE_RECRUIT_STREAKS: 'grepbot:village-recruit-streaks',
    WEBHOOK_RATELIMIT: 'grepbot:webhook-ratelimit',
    WEBHOOK_PENDING: 'grepbot:webhook-pending',
  };

  const PRIORITY_ORDER_DEFAULT = ['culture', 'cave', 'build', 'research', 'trade', 'farm',
    'ruraltrade', 'rurallevel', 'recruit', 'villrecruit', 'merchant', 'pttrade', 'favor', 'wonder', 'hero', 'godspell', 'spy'];
  const CONFIG_VER_CURRENT = 12;

  const WORLD_SCOPED_BASES = new Set([
    STORE.FINDINGS, STORE.FARMS, STORE.FARMS_PARSED, STORE.FARM_RES, STORE.SEEN,
    STORE.TOWNS, STORE.TOWN_RES, STORE.TOWN_GROWTH_HIST, STORE.THRESH, STORE.ALERTED,
    STORE.NEXT_FARM, STORE.NEXT_TOWNS, STORE.BANDIT_LOG,
    STORE.CSRF, STORE.FARM_ACTION, STORE.COLLECT_TPL, STORE.CLAIM_TPL, STORE.ACCEPT_UNITS_TPL,
    STORE.IB_ACTION, STORE.IB_ACTION_R, STORE.FARM_OPTION_MAP, STORE.FARM_LOYALTY_TECH, STORE.FARM_SLEEP_DAY, STORE.FARM_PROFIT, STORE.FARM_TRAVEL, STORE.FARM_CLAIMS_TODAY, STORE.FARM_CLAIMS_DAY,
    STORE.QUEST_REWARDS, STORE.QUEST_HISTORY,
    STORE.ATTACK_TPL, STORE.CANCEL_TPL, STORE.HERO_TPL, STORE.HERO_EQUIP_SUGGEST, STORE.ATTACK_PLAN, STORE.ATTACK_HISTORY, STORE.ATTACK_RECENT, STORE.CAPTCHA,
    STORE.AB_TARGETS, STORE.CAVE_TOWNS, STORE.EMERGENCY_LAST,
    STORE.RESEARCH_TARGETS, STORE.CITY_TEMPLATES, STORE.TOWN_GROUPS, STORE.DUMP_SINKS,
    STORE.MERCHANT_WISH, STORE.FAVOR_CFG, STORE.WONDER_CFG, STORE.WONDER_SPENT,
    STORE.CULTURE_GOLD_SPENT,
    STORE.RECRUIT_TARGETS, STORE.PRIORITY_ORDER,
    STORE.PLAYER_NOTES, STORE.WATCHLIST, STORE.ALLIANCE_NOTES, STORE.NAP_STATUS, STORE.SPY_CFG, STORE.SPY_HISTORY, STORE.SPY_TPL,
    STORE.CAPTCHA_GLOBAL_UNTIL,
    STORE.SERVER_COOLDOWN, STORE.QUEST_CLAIM_FAIL, STORE.DODGE_QUEUE,
    STORE.TRADE_ROUTES, STORE.AUTO_TRADE_ROUTES, STORE.TX_STATE, STORE.CIRCUITS, STORE.AB_ORDER, STORE.AB_OPTIMAL_ORDER, STORE.PLANNER_CFG, STORE.GOAL_PROFILES, STORE.TOWN_GOALS, STORE.VIRTUAL_QUEUE, STORE.VIRTUAL_QUEUE_OVERRIDES, STORE.NATIVE_QUEUE, STORE.BUILD_SWAP_IGNORE, STORE.PROFILE_AUTO_CFG, STORE.PROFILE_AUTO_LAST, STORE.PREDICT_CFG, STORE.DEFENSE_CFG, STORE.DEFENSE_HISTORY, STORE.MILITIA_CFG, STORE.SUPPORT_CFG, STORE.SUPPORT_LAST_SEND, STORE.SUPPORT_TEMPLATE, STORE.DODGE_RETURNS, STORE.HEALTH, STORE.SNAPSHOTS, STORE.CLIENT_FP, STORE.SAFE_MODE, STORE.SIM_CFG, STORE.WHY_LOG, STORE.DECISIONS, STORE.DECISION_SKIPS, STORE.CONFIG_VER, STORE.CONFIG_UNDO, STORE.CONFIG_REDO,
    STORE.FARM_LOYALTY_SEEN, STORE.FARM_TEACH_BANNER,
    STORE.TPL_HEALTH, STORE.LAST_SEEN_TS, STORE.WATCH_HITS, STORE.WONDER_FAVOR_TPL,
    STORE.SPELL_COOLDOWN,
    // endpoint availability is a property of the world's client, not of the user
    STORE.FARM_SCRAPE, STORE.FARM_SCRAPE_STATE, STORE.TOWN_ACTION, STORE.TOWN_LIST_ACTION,
    STORE.PT_TRADE_TPL, STORE.PT_VIEW_URL,
    STORE.WEBHOOK_RATELIMIT, STORE.WEBHOOK_PENDING,
    // An arm window authorises writes against ONE world. Carrying it across a
    // world switch would hand the AI a live window it was never granted there.
    STORE.RELAY_ARM_UNTIL,
  ]);
